### ISSUE TITLE
Support for psr/http-message 2

### ISSUE THREAD

**Issue by Rastusik** [ackintosh/ganesha#106]
Hi,

it would be nice to loosen the dependency on `psr/http-message` to something like `^1.1 || ^2.0` because quite a lot other packages depend on this package.

Thanks

**Comment by ackintosh** [comment]
@Rastusik Looks good. 💡 Please let me know if you would like to file a PR for this issue.

**Comment by ackintosh** [comment]
[v3.1.2](https://github.com/ackintosh/ganesha/releases/tag/3.1.2) has been released. Thanks for your contribution!
