### ISSUE TITLE
Redis Adapter does not initialise status

### ISSUE THREAD

**Issue by Sertion** [ackintosh/ganesha#27]
The Redis adapter will never be able to `loadStatus` successfully as it will always exit with `Failed to load status`. The status is therefor never set. In the same situation in the `Memcached` adapter it will initialise the status with `Ganesha::STATUS_CALMED_DOWN`.

The issues can clearly be seen by subscribing to the Ganesha instance.

**Comment by ackintosh** [comment]
@Sertion Thanks for reporting the issue! I'll investigate the cause of the issue on this weekend.

**Comment by Sertion** [comment]
Great news! Thank you for looking into the issue!
