### ISSUE TITLE
Adapter Redis

### ISSUE THREAD

**Issue by chengangcode** [ackintosh/ganesha#34]
GaneshaTest.php
`namespace Ackintosh;

use Ackintosh\Ganesha\Builder;
use Ackintosh\Ganesha\Storage\Adapter\Redis;

class GaneshaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    private $service = 'GaneshaTestService';

    /**
     * @var \Redis
     */
    private $r;

    public function setUp()
    {
        parent::setUp();
        $this->r = new \Redis();
        $this->r->connect('127.0.0.1');
        $this->r->flushAll();
    }

    /**
     * @test
     */
    public function recordsFailureAndTrips()
    {
        $ganesha = $this->buildGanesha(2);
        $this->assertTrue($ganesha->isAvailable($this->service));

        $ganesha->failure($this->service);
        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));
        // it does not affect other services.
        $this->assertTrue($ganesha->isAvailable('other' . $this->service));
    }

    /**
     * @test
     */
    public function recordsSuccessAndClose()
    {
        $ganesha = $this->buildGanesha(2);
        $ganesha->failure($this->service);
        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));

        $ganesha->success($this->service);
        $this->assertTrue($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function notifyTripped()
    {
        $ganesha = $this->buildGanesha(
            2,
            10
        );

        $receiver = $this->getMockBuilder('\stdClass')
            ->setMethods(['receive'])
            ->getMock();
        $receiver->expects($this->once())
            ->method('receive')
            ->with(Ganesha::EVENT_TRIPPED, $this->service, '');

        $ganesha->subscribe(function ($event, $service, $message) use ($receiver) {
            $receiver->receive($event, $service, $message);
        });

        $ganesha->failure($this->service);
        $ganesha->failure($this->service);
    }

    /**
     * @test
     */
    public function withMemcached()
    {
        $ganesha = Builder::buildWithCountStrategy([
            'failureCountThreshold' => 1,
            'adapter' => new Redis($this->r),
            'intervalToHalfOpen' => 10,
        ]);

        $this->assertTrue($ganesha->isAvailable($this->service));
        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function failureCountMustNotBeNegative()
    {
        $ganesha = $this->buildGanesha(1);

        $ganesha->success($this->service);
        $ganesha->success($this->service);
        $ganesha->success($this->service);
        $this->assertTrue($ganesha->isAvailable($this->service));

        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function withIntervalToHalfOpen()
    {
        $ganesha = $this->buildGanesha(
            1,
            1
        );

        $this->assertTrue($ganesha->isAvailable($this->service));
        // record a failure, ganesha has trip
        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));
        // wait for the interval to half-open
        sleep(2);
        // half-open
        $this->assertTrue($ganesha->isAvailable($this->service));
        // after half-open, service is not available until the interval has elapsed
        $this->assertFalse($ganesha->isAvailable($this->service));
        // record a success, ganesha has close
        $ganesha->success($this->service);
        $this->assertTrue($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function disable()
    {
        $ganesha = $this->buildGanesha(1);

        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));

        Ganesha::disable();
        $this->assertTrue($ganesha->isAvailable($this->service));

        Ganesha::enable();
        $this->assertFalse($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function reset()
    {
        $ganesha = $this->buildGanesha(1);

        $ganesha->failure($this->service);
        $this->assertFalse($ganesha->isAvailable($this->service));

        // For making sure that \Memcached::getAllKeys() (be called by Ganesha::reset()) takes ALL keys, we need to wait a moment...
        sleep(1);

        $ganesha->reset();
        $this->assertTrue($ganesha->isAvailable($this->service));
    }

    /**
     * @test
     */
    public function withRateStrategy()
    {
        $ganesha = Builder::build([
            'adapter' => new Redis($this->r),
            'timeWindow' => 3,
            'failureRateThreshold' => 50,
            'minimumRequests' => 1,
            'intervalToHalfOpen' => 10,
        ]);

        $this->assertTrue($ganesha->isAvailable('test'));

        $ganesha->failure('test');
        $ganesha->failure('test');
        $ganesha->failure('test');
        $ganesha->success('test');
        $ganesha->success('test');

        $this->assertFalse($ganesha->isAvailable('test'));
    }

    private function buildGanesha(
        $threshold,
        $intervalToHalfOpen = 10
    )
    {
        return Builder::buildWithCountStrategy([
            'failureCountThreshold' => $threshold,
            'adapter' => new Redis($this->r),
            'intervalToHalfOpen' => $intervalToHalfOpen,
        ]);
    }
}`

Test Result：
Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:51 

Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:64 

Expectation failed for method name is equal to <string:receive> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:109
 
Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:125
 
Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:141
 
Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:161
 
Failed asserting that true is false.
 D:\wwwroot\ganesha\tests\Ackintosh\GaneshaTest.php:178
 
Time: 863 ms, Memory: 8.00MB

FAILURES!
Tests: 9, Assertions: 14, Failures: 8.

**Comment by ackintosh** [comment]
Hi @chengangcode , thank you for reporting this issue.

I've run the tests locally with latest master but the failures aren't reproduced.

```sh
$ docker-compose up
Starting mongo     ... done
Starting redis     ... done
Starting memcached ... done
Starting server    ... done
Starting client    ... done
...
...

$ docker-compose run --rm -w /tmp/ganesha -u ganesha client vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

...............................................................  63 / 102 ( 61%)
.......................................                         102 / 102 (100%)

Time: 39.12 seconds, Memory: 14.00MB

OK (102 tests, 160 assertions)
```

Could you please let me know the versions you are using? (Ganesha, PHP, OS)

**Comment by happylhb** [comment]
**Builder::buildWithCountStrategy  use  RedisAdapter** 

docker-compose run --rm -w /tmp/ganesha -u ganesha client vendor/bin/phpunit Ackintosh/GaneshaTest /tmp/ganesha/tests/Ackintosh/GaneshaTest.php
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

FFF.FFFF.                                                           9 / 9 (100%)

Time: 928 ms, Memory: 8.00MB

There were 7 failures:

1) Ackintosh\GaneshaTest::recordsFailureAndTrips
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:42

2) Ackintosh\GaneshaTest::recordsSuccessAndClose
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:55

3) Ackintosh\GaneshaTest::notifyTripped
Expectation failed for method name is equal to <string:receive> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

4) Ackintosh\GaneshaTest::failureCountMustNotBeNegative
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:116

5) Ackintosh\GaneshaTest::withIntervalToHalfOpen
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:132

6) Ackintosh\GaneshaTest::disable
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:152

7) Ackintosh\GaneshaTest::reset
Failed asserting that true is false.

/tmp/ganesha/tests/Ackintosh/GaneshaTest.php:169

FAILURES!
Tests: 9, Assertions: 14, Failures: 7.

**Comment by happylhb** [comment]
@ackintosh

**Comment by ackintosh** [comment]
@happylhb Thanks your comment. You mean that the unit tests fails if we set Redis adapter [here](https://github.com/ackintosh/ganesha/blob/8e3db93f1691a7433372082fa1bd39c457606ac4/tests/Ackintosh/GaneshaTest.php#L207) instead of the Memcached adapter?

**Comment by happylhb** [comment]
@ackintosh yes

**Comment by ackintosh** [comment]
@happylhb Unfortunately Redis Adapter doesn't support the Count strategy for now. 😢 

https://github.com/ackintosh/ganesha/blob/df94cbabbe8e3ad892cbf1a98c672f8286d63ff4/src/Ganesha/Storage/Adapter/Redis.php#L67-L70


https://github.com/ackintosh/ganesha/blob/df94cbabbe8e3ad892cbf1a98c672f8286d63ff4/src/Ganesha/Storage/Adapter/Redis.php#L87-L90


From your comment, I've noticed we should update that make Ganesha throws Exception if using Redis Adapter with the counting strategy so that users can notice that is unsupported. 💡

**Comment by ackintosh** [comment]
Now we can notice that an adapter doesn't support the strategy as an exception is thrown if so.
https://github.com/ackintosh/ganesha/pull/36

And I've opened the issue to track the status of a support for Redis + Count.
https://github.com/ackintosh/ganesha/issues/37
