### ISSUE TITLE
Documentation on strategies

### ISSUE THREAD

**Issue by asad-awadia** [ackintosh/ganesha#39]
Can you add more documentation on the two strategy and how they work and what the parameters mean?

**Comment by asad-awadia** [comment]
@ackintosh

**Comment by ackintosh** [comment]
Thanks for this issue @asad-awadia. I'll update the README on this weekend and let you know when I've done.

**Comment by ackintosh** [comment]
@asad-awadia  I've updated the README. Please let me know if you have any questions. 😃
