### ISSUE TITLE
Packagist not listing v0.4.2

### ISSUE THREAD

**Issue by boekkooi-fresh** [ackintosh/ganesha#46]
Good morning/afternoon/evening,

I was updating ganesha and noticed that it was not picking up the latest 0.4.2 version from https://packagist.org/packages/ackintosh/ganesha.
Maybe you can have a look and refresh the package manually?

Thanks in advance!

**Comment by ackintosh** [comment]
Oh..., let me check it. 👀  Thanks!

**Comment by ackintosh** [comment]
It seems that the webhook integration had been expired. I've updated it, and confirmed that v0.4.2 has picked up on Packagist. 🙆‍♂

**Comment by boekkooi-fresh** [comment]
Thanks for the quick fix!
