### ISSUE TITLE
Symfony HttpClient Integration

### ISSUE THREAD

**Issue by pvgnd** [ackintosh/ganesha#68]
Guzzle Middleware is available out of the box, it would nice to have also a Symfony HttpClient (https://github.com/symfony/http-client) integration available out of the box

**Comment by ackintosh** [comment]
@pvgnd Thank you for this issue and the PRs! I'll review the PRs on this weekend. 😉

**Comment by pvgnd** [comment]
I will take some time to fix some issues in tests. Thanks for the first review
