### ISSUE TITLE
[GuzzleMiddleware + GaneshaHttpClient] Option to trigger failure on 5xx response

### ISSUE THREAD

**Issue by pvgnd** [ackintosh/ganesha#73]
It would be nice to be able to configure GuzzleMiddleware & GaneshaHttpClient to trigger failure instead of success on 5xx response from the server.  

For example, a service responding 500 errors because of an overloaded database would be happy that Ganesha break off.

**Comment by pvgnd** [comment]
I will start to work on this feature when GaneshaHttpClient will be merged

**Comment by ackintosh** [comment]
@pvgnd Thanks for this issue! It looks a good idea.

I will have another look for https://github.com/ackintosh/ganesha/pull/69 (probably on this weekend).
