### ISSUE TITLE
APC adapter

### ISSUE THREAD

**Issue by ackintosh** [ackintosh/ganesha#8]

**Comment by 1ma** [comment]
May I ask why did you write off that idea? Wouldn't it make sense to have an storage backend which is not a remote service itself?

**Comment by ackintosh** [comment]
Thank you for your comment!

I was not sure if adding APC adapter is worth at that time but I've found out that it's makes sense from your comment. 💡

**Comment by ackintosh** [comment]
Reopened this issue. 🚀

**Comment by ackintosh** [comment]
APCu adapter has been released as v1.1.0 🎉 Thank you @MikkelPaulson !
